" NOTES
" cursorline(i.e. cul) and relativenumbers were slowing down vim
" use 's' or <space> for search

source ~/.vim/vundle_plugins.vim
set encoding=utf-8
let mapleader = ","

" Mappings
" noremap <Up> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
" noremap <Down> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
" noremap <Left> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
" noremap <Right> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
" inoremap <Up> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
" inoremap <Down> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
" inoremap <Left> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
" inoremap <Right> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>

" --- backup and swap files ---
" I save all the time, those are annoying and unnecessary...
set nobackup
set nowritebackup
set noswapfile
" --- remove sounds effects ---
set noerrorbells
set visualbell

nmap s <Plug>(easymotion-s2)
nmap <Space> <Plug>(easymotion-sn)
nmap <Leader>j <Plug>(easymotion-j)
nmap <Leader>k <Plug>(easymotion-k)

noremap <F5> <ESC>:NERDTreeToggle<CR>
inoremap <F5> <ESC>:NERDTreeToggle<CR>
vnoremap <F5> <ESC>:NERDTreeToggle<CR>

nnoremap / $

inoremap $1 ()<esc>i
inoremap $2 []<esc>i
inoremap $3 {}<esc>i
inoremap $4 {<esc>o}<esc>O
inoremap $q ''<esc>i
inoremap $e ""<esc>i

" Abbreviations
iab xdate <c-r>=strftime("%d/%m/%y %H:%M:%S")<cr>

" While searching in Command Mode
"set path+=**
set path=$PWD/**
" Display all matching files when we tab complete
set wildmenu

" Colors :D
colorscheme neodark
" Use WSL's background color
highlight Normal ctermbg=None guifg=white 

" Enable lightline
set laststatus=2
" Instant mode change display on lightline
set timeoutlen=1000 ttimeoutlen=0 

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_color_change_percent = 3
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

" Vim configs
" set number relativenumber
set showcmd

highlight CursorLine ctermbg=233
" set cul

highlight ColorColumn ctermbg=232
set colorcolumn=101

set nocompatible
filetype plugin on
syntax on
