source ~/.vim/vundle_plugins.vim
set encoding=utf-8
let mapleader = ","

" Mappings
noremap <Up> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
noremap <Down> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
noremap <Left> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
noremap <Right> i<Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
inoremap <Up> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
inoremap <Down> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
inoremap <Left> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>
inoremap <Right> <Space>Don't<Space>Be<Space>A<Space>Loser!<Space><ESC>

nmap s <Plug>(easymotion-s2)
nmap <Space> <Plug>(easymotion-sn)
nmap <Leader>j <Plug>(easymotion-j)
nmap <Leader>k <Plug>(easymotion-k)

noremap <F5> <ESC>:NERDTreeToggle<CR>
inoremap <F5> <ESC>:NERDTreeToggle<CR>
vnoremap <F5> <ESC>:NERDTreeToggle<CR>

" Colors :D
colorscheme neodark
set background=dark
" Use WSL's background color
highlight Normal ctermbg=None guifg=white 

" Enable lightline
set laststatus=2
" Instant mode change display on lightline
set timeoutlen=1000 ttimeoutlen=0 

let g:indent_guides_enable_on_vim_startup = 1

" Vim configs
set number relativenumber
set showcmd
