#!/usr/bin/bash  

# PROMPT STYLES
export PS1="\[\e[34m\]\A\[\e[m\] \[\e[36m\]\W\[\e[m\] \[\e[36m\]\\$\[\e[m\] "

# ALIASES
alias ll='ls -Gla'
alias untar='tar -zxvf '
alias ipe='curl ipinfo.io/ip'
alias ipi='ipconfig getifaddr en0'
alias c='clear'
alias ls='ls -G'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias df='df -H'
alias du='du -ch'
alias gco='git checkout'
alias gcm='git commit -m '
alias gpull='git pull'
alias gpush='git push'
alias gadd='git add'
alias gfetch='git fetch'
alias gstat='git status'
