source ~/.bashrc
export CHEAT_PATH="$HOME/.local/lib/python3.6/site-packages/usr/share/cheat/"

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\u:\[\033[32m\]\${PWD##*/}\[\033[33m\]\$(parse_git_branch)\[\03    3[00m\] $ "

export AWS_ACCESS_KEY_ID=PRIORITYPROFILE
export AWS_SECRET_ACCESS_KEY=PRIORITYPROFILE

alias dev="cd /mnt/c/Users/jerom/Developer/
